# Generated by Django 5.2.5 on 2025-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')])),
                ('note', models.TextField(blank=True)),
                ('generated_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
