# Generated by Django 5.2.5 on 2025-08-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_moodentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('mood', models.IntegerField(choices=[(1, 'Sad'), (2, 'Neutral'), (3, 'Happy')])),
            ],
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='generated_tip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Very bad / Depressed'), (2, 'Bad / Frustrated'), (3, 'Okay / Neutral'), (4, 'Good / Energetic'), (5, 'Great / Happy')]),
        ),
    ]
