# Generated by Django 5.2.5 on 2025-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moodentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('mood', models.IntegerField(choices=[(1, 'Sad'), (2, 'Neutral'), (3, 'Happy')])),
            ],
        ),
    ]
